name: main

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14"
          - "5.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout tree
        uses: actions/checkout@v4

      - name: set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: realm/*.opam remote/*.opam react/*.opam
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            andreypopp: https://github.com/andreypopp/opam-repository.git

      - name: set-up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - run: opam install realm/*.opam remote/*.opam react/*.opam --deps-only --with-test

      - run: opam exec -- dune build -p realm,remote,react_browser,react_server,react_dream

      - run: opam exec -- dune runtest realm remote react
